# Generated by Django 5.2 on 2025-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Project Name', max_length=100),
            preserve_default=False,
        ),
    ]
